config/routes.rb
Rails.application.routes.draw do
  get 'sessions/create'
  get 'sessions/destroy'

  get "/auth/:provider/callback" => "sessions#create"
  delete "logout" => "sessions#destroy"

  get '/likes/coub/tasks' => 'likes/coub/tasks#index', as: 'tasklist'

  namespace :likes do
   namespace :coub do

    get 'main/index'

    resources :tasks, only: [:index, :destroy, :show, :edit, :update, :patch, :post] do
     post 'pause'
     post 'check'
     get 'open'
     collection do
      delete 'delete_all'
     end
    end

    resources :likes,   only: [:new, :create, :index, :show, :edit, :update, :patch, :post]
    resources :follows, only: [:new, :create, :index, :show, :edit, :update, :patch, :post]

   end
  end

  root 'likes/coub/main#index'

end

app/controllers/likes/coub/follows_controller.rb
require 'v_coub_lib'
#--------------------------------------------------------------------------
class Likes::Coub::FollowsController < ApplicationController
  def index
# список заданий для выполнения на подписки
#   @coub_follow_tasks = CoubFollowTask.where(paused: false, suspended: false, finished: false).where.not(user_id: current_user.id).order(cost: :desc).first(20)
#CHANGE!!!
   @coub_follow_tasks = CoubFollowTask.where(paused: false, suspended: false, finished: false).order(cost: :desc).first(20)
  end
#--------------------------------------------------------------------------
  def new
   @coub_follow_task = CoubFollowTask.new
  end
#--------------------------------------------------------------------------
  def edit
   @coub_follow_task = CoubFollowTask.find(params[:id])
  end
#--------------------------------------------------------------------------
  def show
   @coub_follow_task = CoubFollowTask.find(params[:id])
  end
#--------------------------------------------------------------------------
  def create

   vclib = VCoubLib.new(current_user)

   @coub_follow_task = current_user.coub_follow_tasks.build(task_params)

   etask = CoubTask.get_existing(vclib.channel_id_by_url(@coub_follow_task.url), @coub_follow_task.user_id, @coub_follow_task.type, false, false)

   if etask
    @coub_follow_task = etask
    if @coub_follow_task.update(task_params)
     flash[:success] = "Задание успешно обновлено!"
     redirect_to likes_coub_tasks_path
    else
     render 'new'
    end
    return
   end

   @coub_follow_task[:picture_path] = vclib.get_avatar(@coub_follow_task[:url])
   if @coub_follow_task.save
    flash[:success] = "Задание успешно создано!"
#     redirect_to likes_coub_follow_path(@coub_follow_task)
    redirect_to likes_coub_tasks_path
   else
    render 'new'
   end

  end
#--------------------------------------------------------------------------
  def update
   @coub_follow_task = CoubFollowTask.find(params[:id])
   if @coub_follow_task.update(task_params)
    redirect_to likes_coub_tasks_path
   else
    render 'edit'
   end
  end
#--------------------------------------------------------------------------
  private
  def task_params
   params.require(:coub_follow_task).permit(:user_id, :title, :type, :url, :cost, :item_id, :shortcode, :deleted, :paused, :suspended, :verified, :current_count, :max_count, :members_count, :picture_path, :finished)
  end
#--------------------------------------------------------------------------
end

app/controllers/likes/coub/likes_controller.rb
require 'v_coub_lib'

class Likes::Coub::LikesController < ApplicationController

#--------------------------------------------------------------------------
  def index
   # список заданий для выполнения на лайки
#CHANGE!!!
   @coub_like_tasks = CoubLikeTask.where(paused: false, suspended: false, finished: false).order(cost: :desc).first(20)
#   @coub_like_tasks = CoubLikeTask.where(paused: false, suspended: false, finished: false).where.not(user_id: current_user.id).order(cost: :desc).first(20)
  end
#--------------------------------------------------------------------------
  def new
   @coub_like_task = CoubLikeTask.new
  end
#--------------------------------------------------------------------------
  def edit
   @coub_like_task = CoubLikeTask.find(params[:id])
  end
#--------------------------------------------------------------------------
  def show
   @coub_like_task = CoubLikeTask.find(params[:id])
  end
#--------------------------------------------------------------------------
  def create
   vclib = VCoubLib.new(current_user)
   @coub_like_task = current_user.coub_like_tasks.build(task_params)
   etask = CoubTask.get_existing(vclib.get_coub_id(@coub_like_task.url), @coub_like_task.user_id, @coub_like_task.type, false, false)

   if etask
    @coub_like_task = etask
    if @coub_like_task.update(task_params)
     flash[:success] = "Задание успешно обновлено!"
     redirect_to likes_coub_tasks_path
    else
     render 'new'
    end
    return
   end

   coubjson = vclib.get_coub(@coub_like_task[:url])
   web = coubjson["first_frame_versions"]
   template = web["template"]
   versions = web["versions"]
   template.gsub!(/%{version}/, versions[2])
   @coub_like_task[:picture_path] = template

   if @coub_like_task.save
    flash[:success] = "Задание успешно создано!"
    redirect_to likes_coub_tasks_path
#    redirect_to likes_coub_like_path(@coub_like_task)
   else
    render 'new'
   end
  end

#--------------------------------------------------------------------------
  def update
   @coub_like_task = CoubLikeTask.find(params[:id])
   if @coub_like_task.update(task_params)
    redirect_to likes_coub_tasks_path
   else
    render 'edit'
   end
  end
#--------------------------------------------------------------------------
private
 def task_params
  params.require(:coub_like_task).permit(:user_id, :title, :type, :url, :cost, :item_id, :shortcode, :deleted, :paused, :suspended, :verified, :current_count, :max_count, :members_count, :picture_path, :finished)
 end
#--------------------------------------------------------------------------
end


#{"template"=>"http://storage.akamai.coub.com/get/b118/p/coub/simple/cw_file/1ac600a5433/9e88520fce52b812775d3/%{type}_%{version}_size_1457374269_%{version}.%{type}", "types"=>["mp4"], "versions"=>["big", "med"]}

app/controllers/likes/coub/main_controller.rb
class Likes::Coub::MainController < ApplicationController
  def index
  end
end

app/helpers/likes/coub/coub_follow_task_helper.rb
module Likes::Coub::CoubFollowTaskHelper
end

app/helpers/likes/coub/coub_like_task_helper.rb
module Likes::Coub::CoubLikeTaskHelper
end

app/helpers/likes/coub/coub_tasks_helper.rb
module Likes::Coub::CoubTasksHelper
end

app/helpers/likes/coub/main_helper.rb
module Likes::Coub::MainHelper
end

app/views/likes/coub/tasks/_form.html.slim
= form_for([:likes, @coub_task]) do |f|

  - if @coub_task.errors.any?
    h2
      = @coub_task.errors.count
      | &nbsp;
      = Russian.p(@coub_task.errors.count, "ошибка помешала", "ошибки помешали", "ошибок помешали")
      | &nbsp;создать это задание:
    ul
      - @coub_task.errors.full_messages.each do |msg|
        li= msg

  .form-group
    = f.label :title, "Название:",:class => 'col-lg-4 control-label'
    .col-lg-6
      = f.text_field :title, :class => 'form-control'

  .form-group
    = f.label :url, "Url:", :class => 'col-lg-4 control-label'
    .col-lg-6
      - locurl = f.text_field :url
      = f.text_field :url, :disabled => !@coub_task.new_record?, :class => 'form-control', :required => true
      | &nbsp; Ссылка вида https://coub.com/view/b9t15

  .form-group
    = f.label :members_count, "Сколько лайков накрутить:", :class => 'col-lg-4 control-label'
    .col-lg-6
      = f.number_field :members_count, :maxlength => "6", :class => 'form-control', :required => true
      | &nbsp; Минимум 10

  .form-group
    = f.label :cost, "Вознаграждение за лайк:", :class => 'col-lg-4 control-label'
    .col-lg-6
      = f.number_field :cost, :maxlength => "2", :min => 1, :max => 15, :class => 'form-control', :required => true
      | &nbsp; Минимум 1, Максимум 15

  .form-group
    = f.label :max_count, "Лайков будет списано:", :class => 'col-lg-4 control-label'
    .col-lg-6
      = f.text_field :max_count, :maxlength => "4", :disabled => true, :class => 'form-control'

  .actions
    = f.submit "Отправить задание", :class => 'btn btn-info'

javascript:
  function recountMaxCount() {
    $('#coub_task_max_count').val($('#coub_task_members_count').val() * $('#coub_task_cost').val());
  }

  $('#coub_task_members_count').change(recountMaxCount);
  $('#coub_task_cost').change(recountMaxCount);
  highlightErrors();

app/views/likes/coub/tasks/check.js.erb
<% if @completed%>
  <% if @coub_task.verified? %>
    $('#user_reals').html('<%= current_user.reals %>');
    <%= add_gritter("#{Russian.p(@coub_task.user_bonus, "Начислен", "Начислено", "Начислено")} #{@coub_task.user_bonus} #{Russian.p(@coub_task.user_bonus, "реал", "реала", "реалов")}", :title => "Уведомление", :time => 2000, :image => :success, :nodom_wrap => true) %>
  <% else%>
    $('#user_money').html('<%= current_user.money %>');
    <%= add_gritter("#{Russian.p(@coub_task.user_bonus, "Начислен", "Начислено", "Начислено")} #{@coub_task.user_bonus} #{Russian.p(@coub_task.user_bonus, "лайк", "лайка", "лайков")}", :title => "Уведомление", :time => 2000, :image => :success, :nodom_wrap => true) %>
  <% end%>
<% else %>
  <%= add_gritter('Задание не было выполнено', :title => "Ошибка", :image => :error, :time => 2000, :nodom_wrap => true) %>
<% end %>

app/views/likes/coub/tasks/edit.html.slim
h1 Редактирование задания
p
  = render 'form'
p
  = link_to 'Назад', likes_coub_tasks_path

app/views/likes/coub/tasks/index.html.slim
- if current_user
  .panel.panel-default
    .panel-heading
      h1 Мои заказы Coub
    .panel-body
      = render :partial => 'shared/flash_success', :locals => {:msg => flash[:success] }
      table.table.table-hover.table-condensed
        tr
          th.left-aligned style=("width: 150px;") Название
          th.left-aligned style=("width: 150px;") Тип
          th.left-aligned Цена
          th.left-aligned Израсходовано
          th.left-aligned Осталось
          th.left-aligned
          th.left-aligned
          th.left-aligned

          - @coub_tasks.each do |task|
            - if task[:finished] == false
              tr id = "task-#{task.id}"
                td.left-aligned = link_to truncate(task.title, :length => 50), NoRef.hide(task.url), :target => "_blank", :rel => "noreferrer"
                - if task.type == "CoubLikeTask"
                  td.left-aligned = "Лайк"
                - else
                  td.left-aligned = "Подписка"
                td.left-aligned = task.cost
                td.left-aligned = task.max_count
                td.left-aligned = task.current_count

                - if task.type == "CoubLikeTask"
                  td.left-aligned = link_to raw('<i class="glyphicon glyphicon-pencil"></i>'), edit_likes_coub_like_path(task), style: 'color:#17B01F;'
                - else
                  td.left-aligned = link_to raw('<i class="glyphicon glyphicon-pencil"></i>'), edit_likes_coub_follow_path(task), style: 'color:#17B01F;'

                - if task.paused
                  td.left-aligned = link_to raw('<i class="glyphicon glyphicon-play"></i>'), likes_coub_task_pause_path(task.id), style: 'color:#193FE6;', method: :pause
                - else
                  td.left-aligned = link_to raw('<i class="glyphicon glyphicon-pause"></i>'), likes_coub_task_pause_path(task.id), style: 'color:#E67F19;', method: :pause, data: { confirm: "Вы уверены?" }

                td.left-aligned = link_to raw('<i class="glyphicon glyphicon-remove"></i>'), likes_coub_task_path(task), style: 'color:#EB0E45;', method: :delete, data: { confirm: "Вы уверены?" }

  br/
  .centered-text
    h2
      center
        strong
         = link_to 'Новое задание на накрутку лайков', new_likes_coub_like_path
         br/
         br/
         = link_to 'Новое задание на накрутку подписчиков', new_likes_coub_follow_path
         br/
         br/
         = link_to 'Удалить все свои задания', delete_all_likes_coub_tasks_path, method: :delete, data: { confirm: "Вы уверены?" }
         br/
         br/
         = link_to 'Выполнить задания на лайки', likes_coub_likes_path
         br/
         br/
         = link_to 'Выполнить задания на подписки', likes_coub_follows_path
         br/
         br/
         = link_to "Выход из Coub и переход на главную страницу Coub Likes", logout_path, method: :delete

  .centered-text
    center
     .alert.alert-warning
       strong
         table border = "1"
           tr
             th &nbsp;Ваш баланс: #{current_user.money}&nbsp;

- else
  p
    h1
      |  Вход через Coub
      br
      = link_to image_tag("coub.jpg", alt: "Вход через Coub"), "/auth/coub"


javascript:
  | $('#tlp').tooltip();

app/views/likes/coub/tasks/new.html.slim
h1 Новое задание
p На этой странице вы можете создать новое задание для накрутки лайков Coub.
p Для этого заполните форму ниже и нажмите кнопку "Отправить задание".
p Постепенно на нужной странице будут накручиваться сердечки.
p
  = render 'form'
p
  = link_to 'Назад', likes_coub_tasks_path

app/views/likes/coub/tasks/show.html.slim
h3
  center
    table border = "1"
      tr
        td
          strong Название
        td
          = @coub_task.title
      tr
        td
          strong Адрес ссылки, где накрутить лайки
        td
          = link_to @coub_task.url
      tr
        td
          strong Сколько лайков накрутить
        td
          = @coub_task.members_count
      tr
        td
          strong Вознаграждение за лайк
        td
          = @coub_task.cost
      tr
        td
          strong Лайков будет списано
        td
          = @coub_task.max_count
      tr
        td
          strong Приостановлено?
        td
          - if @coub_task.paused
            |  Да
          - else
            |  Нет
      tr
        td
          strong Выполнено?
        td
          - if @coub_task.finished
            |  Да
          - else
            |  Нет
h3
  center
    table
      tr
        td = link_to 'Редактировать', edit_likes_coub_task_path(@coub_task)
        td &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        td = link_to 'Удалить', likes_coub_task_path(@coub_task), method: :delete, data: { confirm: "Вы уверены?" }
        td &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        td = link_to 'Назад', likes_coub_tasks_path